### ISSUE TITLE
Can't access items by key

### ISSUE THREAD

**Issue by lefty2** [mabdelazim/Random-Access-Map#1]
I like your class, but it's lacking a function to retrieve the item like the find function in a normal stl map:
This does not compile:
	RandomAccessMap<int, int> m_mapRand;
	RandomAccessMap<int, int>::iterator iterMap;
	iterMap = m_mapRand.find(randValue);

There is a find function, but it's return value is a boolean... it only tells you that the key exists, but there is no way to retrieve the value

**Comment by mabdelazim** [comment]
Thanks  for  this.
I can fix this by this week.
If you  are able to fix  it. feel  free to do that, and I can add it to git
hub

On Dec 3, 2016 2:41 PM, "lefty2" <notifications@github.com> wrote:

I like your class, but it's lacking a function to retrieve the item like
the find function in a normal stl map:
This does not compile:
RandomAccessMap<int, int> m_mapRand;
RandomAccessMap<int, int>::iterator iterMap;
iterMap = m_mapRand.find(randValue);

There is a find function, but it's return value is a boolean... it only
tells you that the key exists, but there is no way to retrieve the value

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mabdelazim/Random-Access-Map/issues/1>, or mute the
thread

**Comment by lefty2** [comment]
Unfortunately, I'm not any good at template code. I think I'll have to leave you do it, but there's no rush. I made a quick and dirty work around for myself.

**Comment by mabdelazim** [comment]
Fix done, Now find returns iterator.
has_key no returns checks for the key
